$params = @{
    subject = 'CN=PowerShell code signing Cert'
    type = 'codeSigning'
    CertStoreLocation = 'Cert:\CurrentUser\my'
    hashAlgorithm = 'sha256'
}
$cert = New-SelfSignedCertificate @params 
# SIG # Begin signature block
# MIIFdAYJKoZIhvcNAQcCoIIFZTCCBWECAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCaSEtqOb/3yi8N
# /oHXMJn+7vgITUAvblTJQJ8QeJfSQ6CCAvQwggLwMIIB2KADAgECAhBdKD/oPVn3
# mU6pQBrXgpC2MA0GCSqGSIb3DQEBCwUAMBAxDjAMBgNVBAMMBWhhbGxvMB4XDTI0
# MDUyMzA3NTM1N1oXDTI1MDUyMzA4MTM1N1owEDEOMAwGA1UEAwwFaGFsbG8wggEi
# MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDPs8rNSurHaqWBcmyMcL/djTtM
# t5G6gT6GHRzNPGF1hxO56BAenUvMgUxS7rwbMPhku6MuJPG2la6TmNTWO5HWQw7n
# DdnyiBZh3I02lMyycUrRNk6/06RzTmSzHxcFSuQL88nJdRSCuLeWHWAQnxSKi9IW
# sXqv/+OkAqPu1Ir/zJxAke2iSCfxGbJvZo0oj/8C45TbIYtwpVyzb3cBG0cwJO8H
# Gylb55/5kmZcE2FtnKTsVxYORMIg0oM1lKP6cvozNf84tVwwgG6zglzae4wqGIAH
# M3OBksSYYDUdclUv6ARyR9hX60dvGKNDZFPMcrnZmquFXowcfAtl1h7MR1gZAgMB
# AAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNV
# HQ4EFgQUClOjDp4/awn2aWam+KkLYEnpp+IwDQYJKoZIhvcNAQELBQADggEBABCe
# uTtt5WTQqtHl0O2Ol4GLz+vy5lIuz5zsoOGNebSsELsIBmfynqS9/u9LqRWnWTSE
# PUlrUlrpMx0LPzhLW3+cU6SNnpA7No4LHYkC0+6FuyH/pAVOFRcdJUUNxngDDETh
# RJ5WqzVRgMPnwrJuqohXMfH82lGk3wtebtAyFF4HDx6imOFYf4y00+C9MsIxOoa+
# 0aenO1Y/FUDFvdfJRXUJpM+73SK4tZHjlWD0FaYST2WghJemn0S24TUjBl2ZDMxZ
# 3jOEdZxcA1oF82cCzCUkp4h3QO1DHimadaAdSLKXlpXhY3Em8CmsWH3BqUkLCxMA
# IWPTJoItWuLKaaUgUrAxggHWMIIB0gIBATAkMBAxDjAMBgNVBAMMBWhhbGxvAhBd
# KD/oPVn3mU6pQBrXgpC2MA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwx
# CjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGC
# NwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIOr13dmzQhfznwjq
# BIZArsCxpqTU0EYIakjl6QDlY57hMA0GCSqGSIb3DQEBAQUABIIBALLDbfSFB/oW
# xZ1pEsadchvrz3jHpSnoIyG9Jb1AiLo/TFEbJl5IljqZWE9XnSgUZ7ZuUSMMqIdb
# q/eJTmC0OY6kLgSkn0tb+pBA4OliYp49ELKwooR74mBrWeCJ6I24ct2dyf7BAZyx
# 5yf28a6qqtJ37o8YSheq2Hdj8irlCf/cQ9FinMrpIa/7fdqAvr7ITSGi+a8qySrt
# Kw+GiYO2TOTIRg8y43ZyvpAh/srGn/Q4gJPuoKiN6A0oeB+n2RyWZgcE1ZbH52Wr
# 8JdVBFInP7C6nTQ6bCCg/DqAU1BBKflPW9xpHU7KbqrnaH1oY0UQPY7igfQ7sAMZ
# hA1oZ3skwZ8=
# SIG # End signature block
